### ISSUE TITLE
Change mariculture configs for kelp chests and jewelry

### ISSUE THREAD

**Issue by Crizer** [IBeRamen/Uprising#11]
1)     "Kelp Forest > Chest Chance"=640    if the number can be lowered that would be great  ( the number is in the world gen configs of mariculture). currently its really rare to see kelp chests and as they contain mariulture loot  but only spawn in kelp forests and its a bit of an issue.

2) Enable Books being applied to Jewelry"=false   (this line is in the enchantments config of mariculture) it allows us to be a bit more selective on what we want in mariculture jewelry instead of rolling the dice with the mirror (mariculture enchanter) every time.

**Comment by IBeRamen** [comment]
Will be changed once server is back up. If server side only. If not must wait till next update.

**Comment by IBeRamen** [comment]
Changed both configs server side.

**Comment by IBeRamen** [comment]
Updated client side.
